# Disabled for now: no PostgreSQL in current environment.
# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ include "templateapp.fullname" . }}-secret
#   labels:
#     {{- include "templateapp.labels" . | nindent 4 }}
# type: Opaque
# stringData:
#   database-url: "postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
